name: Build & Publish Docker Image

on:
  push:
    branches: ["dev, main"]


jobs:
  build-publish:
    runs-on: ubuntu:latest
    steps:
      - uses: docker/login-action@v2
      - name: Login into Dockerhub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run : ls & pwd
             
         
    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     push: true
    #     tags: user/app:latest


    # - name: Build Docker Image (Golang RESTAPI)
    #   run: docker build . -t 